name: Github Action Test

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v1
      name: Checkout repo
      
    - name: Run App size diff
      uses: ./
      with:
        baseAppPath: 'test/assets/test.apk'
        targetAppPath: 'test/assets/test.apk'
        summaryOutputPath: summary.md

    - name: Print summary
      run: cat summary.md
